# Modified https://stackoverflow.com/a/61574295
# This is a basic workflow to help you get started with Actions

name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      gitBranch:
        description: 'Which branch to update'     
        required: true
        default: 'master'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Sefriol'
          git config --global user.email 'sefriol@users.noreply.github.com'
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream git@github.com:formio/formio.js.git
          git fetch upstream
          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          # git checkout -b feature/x origin/feature/x
          # git merge --no-edit upstream/feature/x
          # git push origin feature/x
          git checkout ${{github.event.inputs.gitBranch}}
          git merge --no-edit upstream/${{github.event.inputs.gitBranch}}
          git push origin ${{github.event.inputs.gitBranch}}
